# anything with wildcards needs quotes since wildcards might contain characters
# that are openly hostile to most shells
cluster:
  mkdir -p cluster_logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-'{rule}-{wildcards}'
    --output='cluster_logs/{rule}/%j-{wildcards}.out'
    --time={resources.time}
default-resources:
  - partition=batch
  - mem_mb=8000
  - time="8:0:0"
set-resources:
        #  - pav_data_ref_contig_table:mem_mb=8000
        #  - pav_data_align_ref_anno_n_gap:mem_mb=8000
        #  - pav_align_get_tig_fa:mem_mb=16000
        #  - pav_align_map:mem_mb=52000
        #  - pav_call_cigar:mem_mb=8000
        #  - pav_call_lg_discover:mem_mb=16000
        #  - pav_call_inv_batch:mem_mb=8000
        #  - pav_call_integrate_sources:mem_mb=8000
        #  - pav_call_cigar_merge:mem_mb=8000
        #  - pav_call_merge_haplotypes_batch:mem_mb=8000
        #  - pav_call_merge_haplotypes_batch:time="16:0:0"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
cluster-cancel: "scancel"
